name: Release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target: 
          - aarch64-linux-android          
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: rustup update stable
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }} 
      - name: build
        run: cargo build --profile githubci
        env:
          CARGO_PROFILE_RELEASE_LTO: "fat"
          CARGO_PROFILE_RELEASE_STRIP: "symbols"
          CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
          
      - name: Prepare lib for release
        run: |
          gh release create "ok" "target/${{ matrix.target }}/githubci/libmtbinloader2.so"

